Repository EatPic/EatPic-iOS, pull requests merged in 2025-07, with the labels that each got.

#4 📝 Docs: README 프로젝트 구조 오류 수정 및 프로젝트 소개 작성
  README.md
Labels: documentation

#5 Revert "📝 Docs: README 프로젝트 구조 오류 수정 및 프로젝트 소개 작성"
  README.md
Labels: bug, documentation

#6 🎉 [Chore] 디자인 시스템 설정
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray010.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray020.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray030.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray040.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray050.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray060.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray070.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray080.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/GrayColor/gray090.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green010.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green020.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green030.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green040.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green050.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/MainColor/green060.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/SubColor/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/SubColor/pink050.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/SubColor/pink060.colorset/Contents.json
  EatPic-iOS/Resources/Colors.xcassets/SubColor/pink070.colorset/Contents.json
  EatPic-iOS/Sources/Screens/ContentView.swift
  EatPic-iOS/Sources/Utilites/Extensions/Color+Extensions.swift
  EatPic-iOS/Sources/Utilites/Extensions/Font+Extensions.swift
Labels: enhancement

#18 ✨ [Feat] PrimaryButton 컴포넌트 제작
  EatPic-iOS/Sources/Components/PrimaryButton.swift
Labels: enhancement, UI

#30 💄 Design: 변경된 디자인시스템(타이포그래피) 반
  EatPic-iOS/Sources/Common/Enum/SignUpFieldType.swift
  EatPic-iOS/Sources/Components/PrimaryButton.swift
  EatPic-iOS/Sources/Screens/ContentView.swift
  EatPic-iOS/Sources/Screens/TabView/MainTabView.swift
  EatPic-iOS/Sources/Utilites/Extensions/Font+Extensions.swift
Labels: Design

#25 ✨ [Feat] PicCardView 컴포넌트 제작
  EatPic-iOS/Sources/Components/PicCardView.swift
Labels: enhancement, UI

#26 ✨ [Feat] recipeDetailCardView 컴포넌트 제작
  EatPic-iOS/Resources/Assets.xcassets/PicCard/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCard/icon_link.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCard/icon_link.imageset/ic_community_link.svg
  EatPic-iOS/Resources/Assets.xcassets/PicCard/icon_navi.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCard/icon_navi.imageset/ic_community_navi.svg
  EatPic-iOS/Sources/Components/ReciptDetailCardView.swift
Labels: enhancement, UI

#28 ✨ [Feat] ReactionBarView 컴포넌트 제작
  EatPic-iOS/Sources/Components/ReactionBarView.swift
Labels: enhancement, UI

#37 💄 [Design] 폰트 수정 이전에 작업되었던 폰트 수정 및 적용
  EatPic-iOS/Sources/Components/PicCardView.swift
  EatPic-iOS/Sources/Components/ReactionBarView.swift
  EatPic-iOS/Sources/Components/ReciptDetailCardView.swift
Labels: UI, Design

#34 ✨[Feat] ProfileImageView 공용 컴포넌트 제작
  EatPic-iOS/Sources/Components/ProfileImageView.swift
Labels: enhancement, UI

#38 ✨ [Feat] LocationSevice & LocationStore 제작
  EatPic-iOS/Sources/Common/Protocol/LocationService.swift
  EatPic-iOS/Sources/Core/Environments/DIContainer.swift
  EatPic-iOS/Sources/Core/Location/LocationServiceImpl.swift
  EatPic-iOS/Sources/Core/Location/LocationStore.swift
  EatPic-iOS/Sources/Utilites/Extensions/CLAuthorizationStatus+Extensions.swift
  Project.swift
Labels: documentation, enhancement

#44 ✨[Feat] TextAreaView 컴포넌트 제작
  EatPic-iOS/Sources/Components/TextAreaView.swift
Labels: enhancement, UI

#48 ✨ [Feat] SearchBarView 컴포넌트 구현
  EatPic-iOS/Resources/Assets.xcassets/icon_delete.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/icon_delete.imageset/btn_explore_delete.svg
  EatPic-iOS/Resources/Assets.xcassets/icon_search.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/icon_search.imageset/ic_community_search.svg
  EatPic-iOS/Sources/Components/SearchBarView.swift
Labels: enhancement, UI

#51 ✨ [Feat] UserSessionKeychainService & APIProviderStore 제작
  .swiftlint.yml
  EatPic-iOS/Sources/Common/Enum/KeychainKey.swift
  EatPic-iOS/Sources/Common/Protocol/Networks/TokenProviding.swift
  EatPic-iOS/Sources/Common/Protocol/Services/NetworkService.swift
  EatPic-iOS/Sources/Common/Protocol/Services/UserSessionKeychainService.swift
  EatPic-iOS/Sources/Core/Environments/DIContainer.swift
  EatPic-iOS/Sources/Core/Keychain/KeychainManager.swift
  EatPic-iOS/Sources/Core/Keychain/UserSessionKeychainServiceImpl.swift
  EatPic-iOS/Sources/Core/Networks/AccessTokenRefresher.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/ResponsePlaceholder.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/TokenResponse.swift
  EatPic-iOS/Sources/Core/Networks/DTO/UserInfo.swift
  EatPic-iOS/Sources/Core/Networks/NetworkServiceImpl.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/APITargetType.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Auth/AuthRouter.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Auth/AuthTargetType.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/TargetTypePlaceholder.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/User/UserTargetType.swift
  EatPic-iOS/Sources/Core/Networks/TokenProvider.swift
  EatPic-iOS/Sources/Core/Store/APIProviderStore.swift
  EatPic-iOS/Sources/Screens/TabView/MainTabView.swift
  EatPic-iOS/Sources/Utilites/Extensions/MoyaProvider+Extensions.swift
  EatPic-iOS/Tests/APITest/AuthAPITest.swift
  EatPic-iOS/Tests/APITest/UserAPITest.swift
Labels: documentation, enhancement, API, refactor

#55 ✨ [Design] BadgeView 디자인 수정
  EatPic-iOS/Sources/Components/BadgeView.swift
Labels: Design

#63 ✨ [Feat] StoreLocationView 컴포넌트 제작
  EatPic-iOS/Resources/Assets.xcassets/Map/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Map/marker.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Map/marker.imageset/Spotlight Marker.svg
  EatPic-iOS/Sources/Common/Protocol/Map/MapRepresentable.swift
  EatPic-iOS/Sources/Common/Protocol/Services/LocationService.swift
  EatPic-iOS/Sources/Components/Map/MapKitView.swift
  EatPic-iOS/Sources/Components/Map/MapViewAdapter.swift
  EatPic-iOS/Sources/Components/Map/MapViewModel.swift
  EatPic-iOS/Sources/Components/Map/Marker.swift
  EatPic-iOS/Sources/Components/Map/Place.swift
  EatPic-iOS/Sources/Components/StoreLocation/StoreLocationView.swift
  EatPic-iOS/Sources/Components/StoreLocation/StoreLocationViewModel.swift
Labels: documentation, enhancement, UI

#65 ✨[Feat] 커스텀 내비게이션바 Modifier 분리 및 View 확장 함수 제공
  EatPic-iOS/Sources/Utilites/Extensions/View+Extensions.swift
  EatPic-iOS/Sources/Utilites/ViewStyle/NavigationHeader/CustomNavigationBarModifier.swift
Labels: enhancement

#67 ♻️ [Refactor]: Component에 속한 파일들 폴더링
  EatPic-iOS/Sources/Components/Badge/BadgeProgressModalView.swift
  EatPic-iOS/Sources/Components/Badge/BadgeView.swift
  EatPic-iOS/Sources/Components/Badge/LockBadgeView.swift
  EatPic-iOS/Sources/Components/Button/PrimaryButton.swift
  EatPic-iOS/Sources/Components/Card/PicCardItemView.swift
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Components/Card/ReciptDetailCardView.swift
  EatPic-iOS/Sources/Components/InputField/FormTextField.swift
  EatPic-iOS/Sources/Components/InputField/TextAreaView.swift
  EatPic-iOS/Sources/Components/Modal/AlertModalView.swift
  EatPic-iOS/Sources/Components/Modal/CameraRecordModalView.swift
  EatPic-iOS/Sources/Components/Modal/CompletionModalView.swift
  EatPic-iOS/Sources/Components/Modal/DecisionModalView.swift
  EatPic-iOS/Sources/Components/Progress/CircleProgressView.swift
  EatPic-iOS/Sources/Components/Reaction/ReactionBarView.swift
  EatPic-iOS/Sources/Components/Search/SearchBarView.swift
  EatPic-iOS/Sources/Components/Sheets/BottomSheetView.swift
  EatPic-iOS/Sources/Components/User/ProfileImageView.swift
Labels: refactor

#69 ✨ [Feat] PicCardWrite 뷰 공통 컴포넌트 추가
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/add_btn.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/add_btn.imageset/btn.pdf
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_link.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_link.imageset/ic_record_link.pdf
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_map.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_map.imageset/ic_record_map.pdf
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_share.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/PicCardWrite/ic_record_share.imageset/ic_record_share.pdf
  EatPic-iOS/Sources/Components/PicCardWrite/PicCardWriteView.swift
Labels: enhancement, UI, Design

#68 :art: [Desing] LoginView UI 구현
  EatPic-iOS/Resources/Assets.xcassets/Login/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Login/apple.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Login/apple.imageset/appleLogin.pdf
  EatPic-iOS/Resources/Assets.xcassets/Login/kakao.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Login/kakao.imageset/kakaoLogin.pdf
  EatPic-iOS/Resources/Assets.xcassets/Login/logo.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Login/logo.imageset/logo.pdf
  EatPic-iOS/Sources/Common/Enum/Login/SignUpFieldType.swift
  EatPic-iOS/Sources/Common/Enum/Login/SocialLoginType.swift
  EatPic-iOS/Sources/Screens/Login/Views/LoginView.swift
Labels: documentation, enhancement, UI

#71 ✨ [Feat] EmailLoginView 제작
  EatPic-iOS/Sources/Common/Enum/Login/SignUpFieldType.swift
  EatPic-iOS/Sources/Common/Protocol/FormFieldType.swift
  EatPic-iOS/Sources/Components/Button/PrimaryButton.swift
  EatPic-iOS/Sources/Components/InputField/FormTextField.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/EmailLoginView.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignUpViewModel.swift
Labels: enhancement, UI, refactor

#77 ✨ [Feat]: ModalView 코드 수정
  EatPic-iOS/Sources/Components/Badge/BadgeProgressModalView.swift
  EatPic-iOS/Sources/Components/Modal/AlertModalView.swift
  EatPic-iOS/Sources/Components/Modal/CameraRecordModalView.swift
  EatPic-iOS/Sources/Components/Modal/CompletionModalView.swift
  EatPic-iOS/Sources/Components/Modal/DecisionModalView.swift
Labels: enhancement

#93 💄 [Design] Custom NavigationBar Background Color 지정
  EatPic-iOS/Sources/Utilites/ViewStyle/NavigationHeader/GlobalNavigationBarStyle.swift
Labels: UI

#88 ✨ [Feat] ExploreMainView UI 구현
  EatPic-iOS/Resources/Assets.xcassets/Explore/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Explore/testImage.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Explore/testImage.imageset/testImage.jpg
  EatPic-iOS/Sources/Components/Search/SearchBarView.swift
  EatPic-iOS/Sources/Screens/Explore/ExploreMainView.swift
  EatPic-iOS/Sources/Screens/TabView/TabViewContent.swift
Labels: enhancement, UI

#86 ✨ Feat: FollowListView UI 구현
  EatPic-iOS/Sources/Screens/FollowListView.swift
Labels: enhancement, UI

#79 ✨[Feat] 회원가입 정보 입력 뷰 (ID 입력 뷰, 닉네임 입력 뷰) UI 구현
  EatPic-iOS/Sources/Common/Enum/Login/SignUpFieldType.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignUpViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupIdView.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupNicknameView.swift
Labels: documentation, enhancement, UI

#81 ✨ [Feat] 회원가입 정보 입력 뷰(프로필) UI 구현
  EatPic-iOS/Resources/Assets.xcassets/Login/profileRegister.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Login/profileRegister.imageset/profileRegister.pdf
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupProfileView.swift
Labels: documentation, enhancement, UI

#91 ✨ [Feat] Calendar Scroll View 제작
  EatPic-iOS/Resources/Assets.xcassets/Calendar/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Calendar/img.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Calendar/img.imageset/img.svg
  EatPic-iOS/Sources/Components/Calendar/Model/CalendarDay.swift
  EatPic-iOS/Sources/Components/Calendar/Model/EatPicDayMeta.swift
  EatPic-iOS/Sources/Components/Calendar/Provide/CalendarDateProvider.swift
  EatPic-iOS/Sources/Components/Calendar/Provide/CalendarDateProviding.swift
  EatPic-iOS/Sources/Components/Calendar/View/CalendarScrollView.swift
  EatPic-iOS/Sources/Components/Calendar/View/CalendarView.swift
  EatPic-iOS/Sources/Components/Calendar/View/Cell.swift
  EatPic-iOS/Sources/Components/Calendar/ViewModel/CalendarViewModel.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
Labels: documentation, enhancement, UI, refactor

#97 ✨ [Feat] Community 탭 페이지들 네비게이션 연결
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Models/Community/CommunityModel.swift
  EatPic-iOS/Sources/Screens/Community/CommunityMainView.swift
  EatPic-iOS/Sources/Screens/Community/FollowListView.swift
  EatPic-iOS/Sources/Screens/Community/OthersProfileView.swift
Labels: enhancement, refactor

#72 ✨ [Feat] Home 뷰 UI 구현 + Navigation
  EatPic-iOS/Resources/Assets.xcassets/Home/Calender/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/Calender/btn_home_next.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/Calender/btn_home_next.imageset/_btn_home_next.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_add.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_add.imageset/_btn_home_add.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_calender.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_calender.imageset/_btn_home_calender.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_ellipsis.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_ellipsis.imageset/btn_home_ellipsis.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_notification.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/HomeMain/btn_home_notification.imageset/btn_home_notification.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/MealStatus/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/MealStatus/exampleSalad.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/MealStatus/exampleSalad.imageset/photo_completed.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img1.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img1.imageset/img1.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img2.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img2.imageset/img2.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img3.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/RecomPicCard/img3.imageset/img3.pdf
  EatPic-iOS/Resources/Assets.xcassets/Home/btn_home_close.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Home/btn_home_close.imageset/btn_home_close.pdf
  EatPic-iOS/Sources/Components/Calendar/View/Cell.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/Community/FollowListView.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/CalenderCardView.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/CalenderNavigationButton.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/CardButtonDetailView/MyMemoView.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/CardButtonDetailView/ReceiptDetailView.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/Carousel/CustomCarousel.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/Carousel/ImageModel.swift
  EatPic-iOS/Sources/Screens/Home/Calender/PicCardEditView.swift
  EatPic-iOS/Sources/Screens/Home/HomeView.swift
  EatPic-iOS/Sources/Screens/Home/Models/MealStatusModel.swift
  EatPic-iOS/Sources/Screens/Home/Models/RecomPicCardModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MealStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/RecomPicCardViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/MealStatusView.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/MyBadgeStatusHomeView.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/RecomPicCardHomeView.swift
  EatPic-iOS/Sources/Screens/Home/Views/MyBadgeStatusAllView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/NotiDetails/CommentNotiView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/NotiDetails/FollowNotiView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/NotiDetails/LikeNotiView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/NotiDetails/ReplyNotiView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/NotificationView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/State/NotiClickState.swift
  EatPic-iOS/Sources/Screens/Home/Views/Notification/State/NotiFollowState.swift
  EatPic-iOS/Sources/Screens/Home/Views/RecomPicCard/RecomPicCardView.swift
  EatPic-iOS/Sources/Screens/TabView/TabViewContent.swift
  EatPic-iOS/Sources/Utilites/Config/ViewStyle/NavigationHeader/CustomNavigationBarModifier.swift
  EatPic-iOS/Sources/Utilites/Config/ViewStyle/NavigationHeader/GlobalNavigationBarStyle.swift
Labels: enhancement, UI
