Repository EatPic/EatPic-iOS, pull requests merged in 2025-08, with the labels that each got.

#103 🐛 [Fix] NavigationRoutingView 타입 추론 실패 및 FollowListView에서 selected 상태값 초기화 실패 오류 해결
  EatPic-iOS/Sources/Components/Search/SearchBarView.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/Community/FollowListView.swift
  EatPic-iOS/Sources/Screens/Home/Calender/CalenderCard/CalenderCardView.swift
Labels: bug

#111 ✨[Feat] 마이페이지 뷰 UI 구현
  EatPic-iOS/Resources/Assets.xcassets/MyPage/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/MyPage/badge.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/MyPage/badge.imageset/ic_mypage_badge.pdf
  EatPic-iOS/Resources/Assets.xcassets/MyPage/bookmark.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/MyPage/bookmark.imageset/ic_mypage_bookmark.pdf
  EatPic-iOS/Resources/Assets.xcassets/MyPage/card.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/MyPage/card.imageset/ic_mypage_card.pdf
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Components/MyPage/MyPageCardView.swift
  EatPic-iOS/Sources/Screens/MyPage/MyPageMainView.swift
  EatPic-iOS/Sources/Screens/TabView/TabViewContent.swift
Labels: documentation, enhancement, Design

#116 ✨ [Feat] Kinfisher를 사용하여 이미지 다운로드 및 캐싱 서비스 제작
  EatPic-iOS/Sources/Common/Protocol/Services/ImageLoaderService.swift
  EatPic-iOS/Sources/Common/State/ImageLoadState.swift
  EatPic-iOS/Sources/Components/Image/NetworkImageView.swift
  EatPic-iOS/Sources/Core/Image/ImageLoaderServiceImpl.swift
  EatPic-iOS/Tests/Image/ImageLoaderServiceTest.swift
Labels: documentation, enhancement

#112 ✨ [Feat] HomeView에 토스트 기능 추가
  EatPic-iOS/Sources/Screens/Calender/CalenderCard/CalenderCardView.swift
Labels: enhancement

#121 ♻️[Refactor] 회원가입 플로우 흩어진 뷰모델 통합
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Screens/Login/ViewModels/LoginViewModel.swift
  EatPic-iOS/Sources/Screens/Login/Views/EmailLoginView.swift
  EatPic-iOS/Sources/Screens/Login/Views/LoginView.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupEmailViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupFlowViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupIdViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupNicknameViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupPasswordViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupEmailView.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupNicknameView.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupPasswordView.swift
  EatPic-iOS/Sources/Screens/SignUp/Views/SignupProfileView.swift
Labels: refactor

#123 ♻️ [Refactor]: DecisionModalView 오른쪽 버튼 색상 변경 가능하게
  EatPic-iOS/Sources/Components/Modal/DecisionModalView.swift
Labels: UI, refactor

#114 ✨[Feat] TextArea/PicCardWriteView 수정 및 PicCardRecordView 데이터 저장 로직 추가
  EatPic-iOS/Sources/Components/InputField/TextAreaView.swift
  EatPic-iOS/Sources/Components/Modal/CameraRecordModalView.swift
  EatPic-iOS/Sources/Components/PicCardWrite/PicCardWriteView.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/Calender/PicCardEditView.swift
  EatPic-iOS/Sources/Screens/Record/Views/HashtagSelectionView.swift
  EatPic-iOS/Sources/Screens/Record/Views/MealTimeSelectionVIew.swift
  EatPic-iOS/Sources/Screens/Record/Views/PicCardRecordView.swift
  EatPic-iOS/Sources/Screens/TabView/TabViewContent.swift
Labels: enhancement, UI

#119 ✨ [Feat] Community탭 - 바텀시트뷰, 토스트뷰 구현
  EatPic-iOS/Resources/Assets.xcassets/Community/send_gray.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Community/send_gray.imageset/community_send.svg
  EatPic-iOS/Resources/Assets.xcassets/Community/send_green.imageset/Contents.json
  EatPic-iOS/Resources/Assets.xcassets/Community/send_green.imageset/btn_community_send.svg
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Common/Enum/Commmunity/ReportTarget.swift
  EatPic-iOS/Sources/Components/Card/PicCardItemView.swift
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Models/Community/CommunityModel.swift
  EatPic-iOS/Sources/Screens/Community/CommentBottomSheetView.swift
  EatPic-iOS/Sources/Screens/Community/CommunityMainView.swift
  EatPic-iOS/Sources/Screens/Community/ReportBottomSheetView.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommentViewModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
  EatPic-iOS/Sources/Screens/Community/Views/FollowListView.swift
  EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
  EatPic-iOS/Sources/Screens/Explore/ExploreSelectedView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicCardView.swift
Labels: enhancement, UI, refactor

#126 ✨ Feat: Record에서 Pic카드 기록시 년월일 시간 불러오도록 수정
  EatPic-iOS/Sources/Screens/Record/Views/PicCardRecordView.swift
Labels: enhancement

#127 ✨ [Feat] community 탭 모달뷰 구현
  EatPic-iOS/Sources/Models/Community/CommunityModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/BlockedUsersManager.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommentViewModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/FollowListViewModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
  EatPic-iOS/Sources/Screens/Community/Views/FollowListView.swift
  EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
Labels: enhancement, UI, refactor

#132 🔧 [Chore] API 연결을 위한 baseURL 등록 및 info plist 설정
  EatPic-iOS/Sources/Utilites/Config/Config.swift
  Project.swift
Labels: infra, API

#150 ✨ [Feature] 이메일 로그인 뷰 유효성 검사 & 메인 탭뷰 전환
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Common/Enum/Login/SignUpFieldType.swift
  EatPic-iOS/Sources/Common/Protocol/FormFieldType.swift
  EatPic-iOS/Sources/Components/InputField/FormTextField.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/AppFlow/AppFlowViewModel.swift
  EatPic-iOS/Sources/Screens/Login/ViewModels/LoginViewModel.swift
  EatPic-iOS/Sources/Screens/Login/Views/EmailLoginView.swift
  EatPic-iOS/Sources/Screens/Login/Views/LoginView.swift
Labels: documentation, enhancement, refactor

#155 ✨ Feat: PicCardView-북마크/댓글/리액션 수 연동
  EatPic-iOS/Sources/Common/Enum/PicCardItemType.swift
  EatPic-iOS/Sources/Components/Card/PicCardItemView.swift
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Components/Reaction/ReactionBarView.swift
  EatPic-iOS/Sources/Models/Community/CommunityModel.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
Labels: enhancement, refactor

#192 ✨ [Feat] 홈화면 환영인사 API 연결
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/GreetingResponse.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/home/HomeTargetType.swift
  EatPic-iOS/Sources/Core/Store/APIProviderStore.swift
  EatPic-iOS/Sources/Screens/Home/HomeView.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/HomeGreetingViewModel.swift
  EatPic-iOS/Sources/Screens/SignUp/ViewModels/SignupIdViewModel.swift
  EatPic-iOS/Sources/Screens/TabView/TabViewContent.swift
Labels: enhancement, API

#205 ✨ [Feat] Bookmark 저장 API 연결
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Core/Data/UseCaseImpl/CreateCardUseCaseImpl.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Bookmark/BookmarkResult.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Bookmark/BookmarkTargetType.swift
  EatPic-iOS/Sources/Core/Store/APIProviderStore.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
Labels: API

#204 ✨ [Feat] 홈화면 진입시 오늘의 식사 카드 조회하기 API 연결
  EatPic-iOS/Sources/Core/Networks/DTO/Response/TodayMealsResponse.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
  EatPic-iOS/Sources/Models/Home/MealStatusModel.swift
  EatPic-iOS/Sources/Screens/Home/HomeView.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/HomeGreetingViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MealStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/MealStatusView.swift
Labels: enhancement, API

#215 ✨ [Feat] 홈화면 진입시 유저 뱃지 리스트 조회
  EatPic-iOS/Sources/Common/Enum/Badge/BadgeModalType.swift
  EatPic-iOS/Sources/Components/Badge/BadgeProgressModalView.swift
  EatPic-iOS/Sources/Components/Badge/BadgeView.swift
  EatPic-iOS/Sources/Components/Card/ReciptDetailCardView.swift
  EatPic-iOS/Sources/Components/Progress/CircleProgressView.swift
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/BadgeDetailDescDTO.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/BadgeListResponse.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/TodayMealsResponse.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/home/HomeTargetType.swift
  EatPic-iOS/Sources/Screens/Home/HomeView.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/BadgeDetailViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/BadgeAll/MyBadgeStatusAllView.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/MyBadgeStatusHomeView.swift
  EatPic-iOS/Sources/Utilites/Extensions/View+Extensions.swift
  EatPic-iOS/Sources/Utilites/ViewStyle/DownsampledRemoteModifier.swift
Labels: enhancement, API

#221 ✨ [Feat] 픽카드 기록하기 뷰모델 제작 및 서버 업로드
  EatPic-iOS/Sources/App/EatPicIOSApp.swift
  EatPic-iOS/Sources/Components/PicCardWrite/PicCardWriteView.swift
  EatPic-iOS/Sources/Core/Data/Error/APIError.swift
  EatPic-iOS/Sources/Core/Data/Mapper/CreateCardMapper.swift
  EatPic-iOS/Sources/Models/Record/PicCardStoreLocation.swift
  EatPic-iOS/Sources/Models/Record/RecordFlowState.swift
  EatPic-iOS/Sources/Screens/Record/ViewModel/PicCardRecordViewModel.swift
  EatPic-iOS/Sources/Screens/Record/ViewModel/RecordFlowViewModel.swift
  EatPic-iOS/Sources/Screens/Record/Views/HashtagSelectingView.swift
  EatPic-iOS/Sources/Screens/Record/Views/PicCardRecorView.swift
  EatPic-iOS/Sources/Screens/Record/Views/PicCardRecordView.swift
  EatPic-iOS/Sources/Utilites/Extensions/View+Extensions.swift
Labels: enhancement, API

#223 ✨Feat: 홈화면 MealStatusView 삭제 API 연결
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/MealStatusCardDeleteResponse.swift
  EatPic-iOS/Sources/Models/Home/MealStatusModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MealStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/MealStatusView.swift
Labels: API

#213 ✨ Feat: 홈화면 추천Pic카드뷰의 카드 하나 눌렀을 때 나오는 카드 단일 피드 API 연결
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/SingleCardFeedResponse.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/RecomPicCardViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/RecomPicSingleCardViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/MainHome/RecomPicCardHomeView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicCardView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicSingleCardView.swift
Labels: API

#230 ✨ [Feat] reaction 삭제 API
  EatPic-iOS/Sources/Components/Card/PicCardItemView.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Reaction/ReactionUserListResult.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Reaction/ReactionTargetType.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/CommunityMainViewModel.swift
Labels: API

#232 ✨ Feat: profile-feed-api 연결
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Card/ProfileFeedResult.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
Labels: API

#233 ✨ [Feat] 캘린더 화면 데이터 조회 API 구현
  EatPic-iOS/Sources/Components/Badge/BadgeProgressModalView.swift
  EatPic-iOS/Sources/Components/Calendar/Model/EatPicDayMeta.swift
  EatPic-iOS/Sources/Components/Calendar/View/CalendarScrollView.swift
  EatPic-iOS/Sources/Components/Calendar/View/CalendarView.swift
  EatPic-iOS/Sources/Components/Calendar/View/Cell.swift
  EatPic-iOS/Sources/Components/Calendar/ViewModel/CalendarScrollViewModel.swift
  EatPic-iOS/Sources/Components/Calendar/ViewModel/CalendarViewModel.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/BadgeDetailDescDTO.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/RecommendedCardsResponse.swift
  EatPic-iOS/Sources/Core/Networks/DTO/Response/Home/TodayMealsResponse.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/home/HomeTargetType.swift
  EatPic-iOS/Sources/Screens/Home/HomeView.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/BadgeDetailViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/HomeGreetingViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MealStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/RecomPicCardViewModel.swift
Labels: documentation, enhancement, API

#241 🐛[ Fix] 다른 사람 프로필 조회시 Card리스트 안나오는 버그 해결
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
Labels: bug, fix

#240 ✨ Feat: BadgeStatusAllView 렌더링 수정 및 뱃지 현황 수정 및 모달 수정
  EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
  EatPic-iOS/Sources/Screens/Home/Views/BadgeAll/MyBadgeStatusAllView.swift
Labels: enhancement

#242 ✨ [Feat] 다른사람 프로필 조회시 팔로워/팔로잉/픽카드 개수 조회 API 구현
  EatPic-iOS/Sources/Core/Networks/DTO/Response/ProfileDetailResult.swift
  EatPic-iOS/Sources/Core/Networks/TargetType/Card/CardTargetType.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/OthersProfileViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/OthersProfileView.swift
Labels: API

#245 ✨ Feat: 잇친들의 Pic카드 불러오기 + 메인 홈뷰에 획득 개수 불러옴
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/Explore/ExploreSelectedView.swift
  EatPic-iOS/Sources/Screens/Home/ViewModels/MyBadgeStatusViewModel.swift
  EatPic-iOS/Sources/Screens/MyPage/Views/MyPageMainView.swift
  EatPic-iOS/Sources/Screens/MyPage/Views/SavedPicCard/SavedPicCardView.swift
  EatPic-iOS/Sources/Screens/MyPage/Views/SavedPicCard/SavedPicCardViewModel.swift
Labels: Design

#248 ✨ Feat: RecomPicCardSingleView에서 프로필/식당위치 이동 적용 + MyPage픽카드뷰들에서도 개별 피드로 네비게이션
  EatPic-iOS/Sources/Core/Navigation/NavigationRoutingView.swift
  EatPic-iOS/Sources/Screens/Home/Views/Recommend/RecomPicSingleCardView.swift
  EatPic-iOS/Sources/Screens/MyPage/Views/AllPicCard/MyAllPicCardView.swift
Labels: enhancement

#252 🐛[Fix] 팔로우 리스트뷰 세그먼트탭 숫자 랜더링 & 커뮤니티 탭 프로필 랜더링 수정
  EatPic-iOS/Sources/Components/Card/PicCardView.swift
  EatPic-iOS/Sources/Screens/Community/ViewModels/FollowListViewModel.swift
  EatPic-iOS/Sources/Screens/Community/Views/CommunityMainView.swift
  EatPic-iOS/Sources/Screens/Community/Views/FollowListView.swift
Labels: bug, fix

#253 🎨 Design: MyPageMainView의 introduction 잘리지 않도록 수정
  EatPic-iOS/Sources/Screens/MyPage/Views/MyPageMainView.swift
Labels: Design
